spring:
  datasource:
    username: ${USERNAME}
    url: jdbc:mysql://localhost:3306/product?createDatabaseIfNotExist=true&serverTimezone=UTC
    password: ${PASSWORD}
  jpa:
    generate-ddl: 'true'
    database-platform: org.hibernate.dialect.MySQL5Dialect
    properties:
      hibernate:
        format_sql: 'true'
        show_sql: 'true'
    hibernate:
      ddl-auto: update
    show-sql: 'true'
server:
  error:
    include-binding-errors: always
    include-message: always
